FROM python:3.10

WORKDIR /code

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git

# Install Python dependencies
RUN pip install -U pip \
    streamlit \
    numpy \
    pandas

# Expose the port on which the Streamlit app will run
EXPOSE 8501

# Copy the application code
COPY . /code

# Change directory and run the Streamlit app
CMD ["bash", "-c", "cd khmernlp/tokenize && streamlit run gui.py"]
